version: "3"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
  app:
    depends_on:
      - mysql
    build: .
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: 'test_db'
      MYSQL_ROOT_PASSWORD: 'password'
    stdin_open: true
    tty: true

volumes:
  my-db: