apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  selector:
    matchLabels:
      app: order-deployment
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
      - name: order
        image: docker.io/geekboii/order_service:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: order-db
                key: MYSQL_HOST
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: order-db
                key: MYSQL_PORT
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                  name: order-db
                  key: MYSQL_DATABASE

